# Generated by Django 3.1.2 on 2020-10-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_number', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('_Muffin', 'Muffin'), ('_Cookie', 'Cookie'), ('_Cupcake', 'Cupcake')], max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItem_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muffinShop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muffinShop.product')),
            ],
        ),
    ]
