# Generated by Django 3.1.2 on 2020-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffinShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
