# Generated by Django 3.1.2 on 2020-10-27 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffinShop', '0002_auto_20201027_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 25, 0, 903054), null=True),
        ),
    ]
